export const scenes = [
{id:'landing',label:'Mở đầu',eyebrow:'MỘT KHU VỰC, NHIỀU NHỊP ĐIỆU',title:'Những nhịp\nphục hồi.',description:'Cùng khám phá cách kể câu chuyện kinh tế ASEAN: từ bức tranh khu vực đến từng quốc gia, rồi đặt những hành trình cạnh nhau.'},
{id:'overview',label:'Toàn cảnh',eyebrow:'01 / BỨC TRANH KHU VỰC',title:'Cùng một điểm xuất phát?',description:'Quy đổi độ mở thương mại về 2012 = 100 để so sánh quỹ đạo của năm nền kinh tế trên cùng một thước đo.'},
{id:'vietnam',label:'Việt Nam',country:'VN',eyebrow:'02 / VIỆT NAM',title:'Theo dấu một hành trình.',description:'Độ mở thương mại của Việt Nam tăng từ 123,2% GDP năm 2012 lên 190,3% năm 2025, tương ứng chỉ số 154,5 so với mốc 100. Năm 2025, chế biến chế tạo chiếm 24,5% GDP và cán cân vãng lai thặng dư 6,4% GDP.'},
{id:'indonesia',label:'Indonesia',country:'ID',eyebrow:'03 / INDONESIA',title:'Đặt quy mô vào bối cảnh.',description:'Độ mở thương mại của Indonesia giảm từ 49,6% GDP năm 2012 xuống 43,4% năm 2025, tương ứng chỉ số 87,5 so với mốc 100. Năm 2025, chế biến chế tạo chiếm 19,1% GDP và cán cân vãng lai gần cân bằng ở mức -0,1% GDP.'},
{id:'thailand',label:'Thái Lan',country:'TH',eyebrow:'04 / THÁI LAN',title:'Nhìn lại đường cơ sở.',description:'Độ mở thương mại của Thái Lan đạt 138,4% GDP năm 2025, gần mức 140,6% của năm 2012 và tương ứng chỉ số 98,4. Sau khi giảm còn 97,7% GDP năm 2020, độ mở đã phục hồi; chế biến chế tạo và cán cân vãng lai năm 2025 lần lượt đạt 23,7% và 2,8% GDP.'},
{id:'malaysia',label:'Malaysia',country:'MY',eyebrow:'05 / MALAYSIA',title:'Một đường, nhiều câu hỏi.',description:'Độ mở thương mại của Malaysia giảm từ 147,8% GDP năm 2012 xuống 139,0% năm 2025, tương ứng chỉ số 94,0 so với mốc 100. Từ mức thấp 116,8% GDP năm 2020, độ mở đã phục hồi; chế biến chế tạo và cán cân vãng lai năm 2025 lần lượt đạt 22,1% và 1,6% GDP.'},
{id:'singapore',label:'Singapore · benchmark',country:'SG',eyebrow:'06 / SINGAPORE · BENCHMARK',title:'Một điểm tham chiếu.',description:'Độ mở thương mại của Singapore giảm từ 369,2% GDP năm 2012 xuống 320,4% năm 2025, tương ứng chỉ số 86,8 nhưng vẫn cao nhất trong năm nền kinh tế. Năm 2025, cán cân vãng lai thặng dư 16,7% GDP, trong khi chế biến chế tạo chiếm 17,4% GDP.'},
{id:'comparison',label:'Đối chiếu',eyebrow:'07 / ĐẶT CẠNH NHAU',title:'So sánh cùng một thước đo.',description:'Thay đổi độ mở thương mại cho biết tỷ trọng xuất khẩu và nhập khẩu trong GDP tăng hay giảm so với năm gốc. Khi độ mở tăng, nền kinh tế có thể hưởng lợi nhiều hơn từ thị trường quốc tế nhưng cũng nhạy cảm hơn với biến động cầu, tỷ giá và chuỗi cung ứng; khi giảm, mức phụ thuộc tương đối vào giao dịch xuyên biên giới thấp hơn, không tự động có nghĩa tăng trưởng tốt hay xấu.'},
{id:'surprise',label:'Góc nhìn khác',eyebrow:'08 / CẤU TRÚC & ĐỐI NGOẠI',title:'Sản xuất mạnh có đồng nghĩa thặng dư cao?',description:'Dữ liệu năm 2025 không cho thấy tỷ trọng chế biến, chế tạo cao luôn đi cùng thặng dư vãng lai lớn. Singapore có tỷ trọng chế biến, chế tạo thấp nhất nhóm (17,4% GDP) nhưng thặng dư vãng lai cao nhất (16,7% GDP), trong khi Việt Nam dẫn đầu về chế biến, chế tạo (24,5% GDP) nhưng thặng dư thấp hơn (6,4% GDP).'},
{id:'methodology',label:'Phương pháp',eyebrow:'09 / METHODOLOGY',title:'Minh bạch từ dữ liệu.',description:'Đọc nguồn, định nghĩa và giới hạn trước khi diễn giải bất kỳ biểu đồ nào.'}
];
